### PR TITLE
User should be directly logged in after new user creation

### LINKED ISSUE #128: User should be directly logged in after new user creation
Dit is volgens mij iets wat nog veranderd moest worden

### PR DESCRIPTION
**Pull request by sajvanwijk**
Fixes #128

I also added a little timeout between the user creation and the login to make it more clear to the user what's going on.

Functional tests: 
Simply create a new user and you'll see the magic happen

### CODE REVIEW

**Comment by Ycreak** [comment]
No timeouts. Can't we solve this with a snackbar informing the user?

**Comment by sajvanwijk** [comment]
Aye aye

**Comment by sajvanwijk** [comment]
Like so?

**Comment by Ycreak** [comment]
Excellent work! I did remove the "user created" message, as it disappears directly because of the "login succesful" message. As the latter provides enough information about the successfulness of the creation, I think we can leave it like this. Otherwise we must find a way to let snackbars wait on eachother :+1:

**Pull request merged**
